services:
  - type: web
    name: billing-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import db; from app import app; with app.app_context(): db.create_all()"
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
    healthCheckPath: /
    autoDeploy: true 